# Build worker image (VM template)
image:
  - Visual Studio 2017

# scripts that are called at very beginning, before repo cloning
init:
  - date /T & time /T
  - git config --global core.autocrlf input
  - set tag_prefix=%APPVEYOR_REPO_TAG_NAME:~0,3%

# clone directory
clone_folder: c:\projects\main

branches:
  only:
    - main

version: '{build}'

skip_non_tags: true

platform:
  - x86

#configuration:
#  - Release
#  - Debug

#xxxskip_tags: true

#environment:
  #matrix:
  #  - generator: "Visual Studio 15"    

matrix:
  fast_finish: true

artifacts:
  - path: '**\*.exe'

build_script:

  - cd %clone_folder%
  - dir


    #- call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat"
    #- msbuild helloworld.sln /p:Configuration=Debug
    #- msbuild helloworld.sln /p:Configuration=Release
    #
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - set
  - nmake wexe

  - dir/s *.exe

  - 7z a dailyupdate-appveyor-%APPVEYOR_REPO_TAG_NAME%.zip *.exe
  - 7z l dailyupdate-appveyor-%APPVEYOR_REPO_TAG_NAME%.zip

  - dir/s *.zip
  #
  # vs2017 32bit
  # call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat"
  # vs2017 64bit
  # call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"

deploy:
    release: $(APPVEYOR_REPO_TAG_NAME)
    tag: $(APPVEYOR_REPO_TAG_NAME)
    description: 'Release description'
    provider: GitHub
    auth_token:
        secure: e9lKkj7uh58VQHYjAvs1eBIDgOqDmde7434f2ABj3WNULRWO4j4vvmmxZcgoSxoI
    artifact: '**\*.zip'          # upload all exe(zip) to release assets
    draft: false
    prerelease: false

    on:
        APPVEYOR_REPO_TAG: true        # deploy on tag push only
        tag_prefix: v1.
        #branch: main

        #on:
        #branch: master
        #APPVEYOR_REPO_TAG: true        # deploy on tag push only
